---
### Part 01 - load initial raw data
---

In [48]:
# import libs
from glob import glob
import os
import lasio
import pandas as pd

In [21]:
# list dir
os.listdir("../data/las")

['AAM-4.las',
 'ALR-4.las',
 'ALR-16.las',
 'TFT-13.las',
 'AAM-10.las',
 'ALR-21.las',
 'ISL-19.las',
 'AAM-14.las',
 'HR-17.las',
 'HR-4.las',
 'AAM-18.las',
 'EMK-1.las',
 'BRK-1.las',
 'AAM-21.las',
 'OUR-2.las',
 'ISL-10.las',
 'HR-13.las',
 'TFT-14.las',
 'TFT-4.las',
 'AAM-6.las',
 'ALR-18.las',
 'ALR-9.las',
 'ISL-8.las',
 'HR-10.las',
 'HR-16.las',
 'ALR-17.las',
 'ALR-13.las',
 'AAM-8.las',
 'HR-7.las',
 'ALR-15.las',
 'TFT-5.las',
 'ISL-2.las',
 'TFT-11.las',
 'ISL-22.las',
 'ISL-13.las',
 'ISL-4.las',
 'ALR-19.las',
 'AAM-1.las',
 'TFT-1.las',
 'AAM-19.las',
 'ISL-16.las',
 'ALR-2.las',
 'GT-2.las',
 'HR-6.las',
 'HMD-5.las',
 'AAM-3.las',
 'ISL-18.las',
 'HR-1.las',
 'HR-2.las',
 'TFT-3.las',
 'MZL-1.las',
 'ALR-6.las',
 'TFT-2.las',
 'HR-11.las',
 'ISL-17.las',
 'AAM-5.las',
 'ALR-11.las',
 'BRK-2.las',
 'GT-1.las',
 'ELG-1.las',
 'ZRZ-1.las',
 'ZRZ-2.las',
 'TFT-12.las',
 'ELG-2.las',
 'GT-3.las',
 'AAM-17.las',
 'TFT-9.las',
 'ALR-5.las',
 'ISL-6.las',
 'ISL-11.las',
 'ISL-15.las',
 'AAM-16.las',
 'ALR-3.las',
 'AAM-2.las',
 'ALR-14.las',
 'ISL-9.las',
 'ALR-10.las',
 'AAM-12.las',
 'AAM-13.las',
 'ISL-14.las',
 'ISL-21.las',
 'ISL-20.las',
 'ISL-5.las']

In [22]:
# locate folder las
las_path = "../data/las"

In [23]:
# list las files
las_files = glob(f"{las_path}/*.las")
len(las_files)

83

In [24]:
# read one well first
las = lasio.read(las_files[0])
las.header

{'Version': [HeaderItem(mnemonic="VERS", unit="", value="2.0", descr=""),
  HeaderItem(mnemonic="WRAP", unit="", value="NO", descr="")],
 'Well': [HeaderItem(mnemonic="STRT", unit="m", value="155.09970504", descr=""),
  HeaderItem(mnemonic="STOP", unit="m", value="2250.0", descr=""),
  HeaderItem(mnemonic="STEP", unit="m", value="0.152", descr=""),
  HeaderItem(mnemonic="NULL", unit="", value="-999.25", descr=""),
  HeaderItem(mnemonic="COMP", unit="", value="SONATRACH", descr="COMPANY"),
  HeaderItem(mnemonic="WELL", unit="", value="AAM-4", descr="WELL"),
  HeaderItem(mnemonic="FLD", unit="", value="Ain Amenas", descr="FIELD"),
  HeaderItem(mnemonic="LOC", unit="", value="Algeria, Lat: 28.120, Lon: 9.525", "),
  HeaderItem(mnemonic="SRVC", unit="", value="Baker Hughes", descr="SERVICE COMP"),
  HeaderItem(mnemonic="DATE", unit="", value="2018-12-16 00:00:00   : Log Export"),
  HeaderItem(mnemonic="PROV", unit="", value="Sahara Central", descr="PROVINCE"),
  HeaderItem(mnemonic="UWI", unit="", value="AAM-4", descr="UNIQUE WELL ID"),
  HeaderItem(mnemonic="API", unit="", value="", descr="API NUMBER")],
 'Curves': [CurveItem(mnemonic="DEPT", unit="m", value="", descr="DEPTH", original_mnemonic="DEPT", data.shape=(13783,)),
  CurveItem(mnemonic="LITHOLOGY_CONFIDENCE", unit="_", value="", descr="LITHOLOGY_CONFIDENCE", original_mnemonic="LITHOLOGY_CONFIDENCE", data.shape=(13783,)),
  CurveItem(mnemonic="LITHOLOGY_CLASS", unit="_", value="", descr="LITHOLOGY_CLASS", original_mnemonic="LITHOLOGY_CLASS", data.shape=(13783,)),
  CurveItem(mnemonic="CALI", unit="in", value="", descr="CALI", original_mnemonic="CALI", data.shape=(13783,)),
  CurveItem(mnemonic="MUDWEIGHT", unit="_", value="", descr="MUDWEIGHT", original_mnemonic="MUDWEIGHT", data.shape=(13783,)),
  CurveItem(mnemonic="ROP", unit="m/h", value="", descr="ROP", original_mnemonic="ROP", data.shape=(13783,)),
  CurveItem(mnemonic="RDEP", unit="ohm.m", value="", descr="RDEP", original_mnemonic="RDEP", data.shape=(13783,)),
  CurveItem(mnemonic="RSHA", unit="ohm.m", value="", descr="RSHA", original_mnemonic="RSHA", data.shape=(13783,)),
  CurveItem(mnemonic="RMED", unit="ohm.m", value="", descr="RMED", original_mnemonic="RMED", data.shape=(13783,)),
  CurveItem(mnemonic="DTC", unit="us/ft", value="", descr="DTC", original_mnemonic="DTC", data.shape=(13783,)),
  CurveItem(mnemonic="NPHI", unit="m3/m3", value="", descr="NPHI", original_mnemonic="NPHI", data.shape=(13783,)),
  CurveItem(mnemonic="PEF", unit="b/e", value="", descr="PEF", original_mnemonic="PEF", data.shape=(13783,)),
  CurveItem(mnemonic="GR", unit="gAPI", value="", descr="GR", original_mnemonic="GR", data.shape=(13783,)),
  CurveItem(mnemonic="RHOB", unit="g/cm3", value="", descr="RHOB", original_mnemonic="RHOB", data.shape=(13783,)),
  CurveItem(mnemonic="DRHO", unit="g/cm3", value="", descr="DRHO", original_mnemonic="DRHO", data.shape=(13783,)),
  CurveItem(mnemonic="DEPTH_MD", unit="_", value="", descr="DEPTH_MD", original_mnemonic="DEPTH_MD", data.shape=(13783,)),
  CurveItem(mnemonic="X_LOC", unit="_", value="", descr="x_loc", original_mnemonic="X_LOC", data.shape=(13783,)),
  CurveItem(mnemonic="Y_LOC", unit="_", value="", descr="y_loc", original_mnemonic="Y_LOC", data.shape=(13783,)),
  CurveItem(mnemonic="Z_LOC", unit="_", value="", descr="z_loc", original_mnemonic="Z_LOC", data.shape=(13783,))],
 'Parameter': [],
 'Other': ''}

In [28]:
# convert to pandas dataframe
df = las.df().reindex()
df.head()

,LITHOLOGY_CONFIDENCE,LITHOLOGY_CLASS,CALI,MUDWEIGHT,ROP,RDEP,RSHA,RMED,DTC,NPHI,PEF,GR,RHOB,DRHO,DEPTH_MD,X_LOC,Y_LOC,Z_LOC
DEPT,,,,,,,,,,,,,,,,,,
155.099705,NaN,NaN,NaN,NaN,14.689068,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
155.251705,NaN,NaN,NaN,NaN,14.670721,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
155.403705,NaN,NaN,NaN,NaN,14.652373,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
155.555705,NaN,NaN,NaN,NaN,14.634027,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
155.707705,NaN,NaN,NaN,NaN,14.615680,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

---
### Part 02 - standardize the data
---

In [49]:
# load all the wells together
dfs = []

for file in las_files:

    las = lasio.read(file)

    df = las.df().reset_index()

    # print(type(df))   # class 'pandas.DataFrame'
    # print(df.columns)

    df.columns = [c.upper() for c in df.columns]

    # well name
    # print(file)    # ../data/las/AAM-4.las
    well = file.split("/")[-1].replace(".las", "")
    # print(well)     # AAM-4

    # region name
    region = well.split("-")[0]
    # print(region)    # AM

    df["WELL"] = well
    df["REGION"] = region

    # print(df.head())

    dfs.append(df)

final_df = pd.concat(dfs, ignore_index=True)

In [50]:
final_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1638107 entries, 0 to 1638106
Data columns (total 29 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   DEPT                  1638107 non-null  float64
 1   LITHOLOGY_CONFIDENCE  851658 non-null   float64
 2   LITHOLOGY_CLASS       844039 non-null   float64
 3   CALI                  882147 non-null   float64
 4   MUDWEIGHT             221139 non-null   float64
 5   ROP                   882925 non-null   float64
 6   RDEP                  1535469 non-null  float64
 7   RSHA                  502830 non-null   float64
 8   RMED                  1417942 non-null  float64
 9   DTC                   1139307 non-null  float64
 10  NPHI                  607362 non-null   float64
 11  PEF                   506252 non-null   float64
 12  GR                    1603270 non-null  float64
 13  RHOB                  830620 non-null   float64
 14  DRHO                  765164 non-null   float64
 15  DEPTH_MD              1538097 non-null  float64
 16  X_LOC                 1538097 non-null  float64
 17  Y_LOC                 1538097 non-null  float64
 18  Z_LOC                 1538097 non-null  float64
 19  WELL                  1638107 non-null  str
 20  REGION                1638107 non-null  str
 21  BS                    1096224 non-null  float64
 22  DTS                   314118 non-null   float64
 23  RXO                   184438 non-null   float64
 24  RMIC                  215362 non-null   float64
 25  SP                    687634 non-null   float64
 26  SGR                   41921 non-null    float64
 27  DCAL                  211900 non-null   float64
 28  ROPA                  627884 non-null   float64
dtypes: float64(27), str(2)
memory usage: 375.6 MB

In [51]:
df.columns

Index(['DEPT', 'LITHOLOGY_CONFIDENCE', 'LITHOLOGY_CLASS', 'CALI', 'RDEP',
       'RSHA', 'RMED', 'SP', 'DTS', 'DTC', 'NPHI', 'PEF', 'GR', 'RHOB', 'DRHO',
       'DEPTH_MD', 'X_LOC', 'Y_LOC', 'Z_LOC', 'WELL', 'REGION'],
      dtype='str')

In [54]:
final_df.describe()

,DEPT,LITHOLOGY_CONFIDENCE,LITHOLOGY_CLASS,CALI,MUDWEIGHT,ROP,RDEP,RSHA,RMED,DTC,...,Y_LOC,Z_LOC,BS,DTS,RXO,RMIC,SP,SGR,DCAL,ROPA
count,1.638107e+06,851658.000000,844039.000000,882147.000000,221139.000000,882925.000000,1.535469e+06,502830.000000,1.417942e+06,1.139307e+06,...,1.538097e+06,1.538097e+06,1.096224e+06,314118.000000,184438.000000,215362.000000,687634.000000,41921.000000,211900.000000,627884.000000
mean,1.876861e+03,1.171018,61714.064817,12.683615,14.336344,439.497073,1.014219e+01,11.337729,4.746521e+00,1.145272e+02,...,6.706163e+06,-1.877706e+03,1.375157e+01,220.132792,-47.969024,9.432302,45.874226,62.320908,9.387180,37.669995
std,1.066126e+03,0.458186,13877.216662,3.572450,44.517034,3547.567194,1.025613e+02,105.359657,6.137791e+01,3.173884e+01,...,1.323480e+05,1.014427e+03,5.103290e+00,82.534531,342.736271,98.429793,74.281951,63.344105,292.584426,91.646967
min,4.880000e-02,1.000000,30000.000000,2.340806,0.127016,-21.495783,1.000000e-04,0.056584,-8.418695e-03,0.000000e+00,...,6.406641e+06,-5.435889e+03,6.000000e+00,79.327354,-999.900024,0.056586,-400.000000,-983.000000,-7.911209,-999.250122
25%,1.003194e+03,1.000000,65000.000000,9.085900,0.161766,14.722836,9.315748e-01,0.825328,9.204937e-01,8.984405e+01,...,6.591174e+06,-2.601157e+03,9.875000e+00,157.653992,0.706932,0.907435,24.724890,27.747322,0.099576,15.285406
50%,1.759820e+03,1.000000,65000.000000,12.409645,1.102403,28.597115,1.407801e+00,1.343230,1.380060e+00,1.120304e+02,...,6.771062e+06,-1.770935e+03,1.225000e+01,197.519257,1.483171,1.646600,48.753498,73.179337,0.395277,25.798542
75%,2.625954e+03,1.000000,65030.000000,14.004926,1.404611,46.939632,2.308210e+00,2.611515,2.238813e+00,1.414047e+02,...,6.803076e+06,-1.054253e+03,1.750000e+01,260.159294,4.021766,4.129066,74.839558,94.457108,0.992176,39.121716
max,5.479040e+03,3.000000,99000.000000,32.111065,185.730927,92429.164063,1.999887e+03,2193.904541,1.999948e+03,2.409352e+02,...,6.856661e+06,-1.088560e+02,4.200000e+01,724.536194,35930.671875,6567.910156,280.842529,963.608582,10010.719727,3989.174316

In [56]:
final_df.isnull().mean().sort_values()

DEPT                    0.000000
WELL                    0.000000
REGION                  0.000000
GR                      0.021267
X_LOC                   0.061052
Y_LOC                   0.061052
DEPTH_MD                0.061052
Z_LOC                   0.061052
RDEP                    0.062656
RMED                    0.134402
DTC                     0.304498
BS                      0.330798
ROP                     0.461009
CALI                    0.461484
LITHOLOGY_CONFIDENCE    0.480096
LITHOLOGY_CLASS         0.484747
RHOB                    0.492939
DRHO                    0.532897
SP                      0.580226
ROPA                    0.616701
NPHI                    0.629229
PEF                     0.690953
RSHA                    0.693042
DTS                     0.808243
MUDWEIGHT               0.865003
RMIC                    0.868530
DCAL                    0.870643
RXO                     0.887408
SGR                     0.974409
dtype: float64